# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 00:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('skoolprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='desc',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='school',
            name='primary',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='school',
            name='schoolid',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='school',
            name='secondary',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='school',
            name='senior',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='school',
            name='since',
            field=models.DateField(default=datetime.datetime(2016, 3, 1, 0, 18, 10, 296000, tzinfo=utc)),
        ),
    ]
